spring:
  application:
    name: e-commerce-application

  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  secret-key: hjkklljgtfftrtr7vgftgjjkkjj
  expiration-time: 86400000


